export default {
  login: 'drjseifu1991',
  id: 51210918,
  node_id: 'MDQ6VXNlcjY1OTk5Nzk=',
  avatar_url: 'https://avatars.githubusercontent.com/u/51210918?s=64&v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/drjseifu1991',
  html_url: 'https://github.com/drjseifu1991',
  followers_url: 'https://api.github.com/users/drjseifu1991/followers',
  following_url: 'https://api.github.com/users/drjseifu1991/following{/other_user}',
  gists_url: 'https://api.github.com/users/drjseifu1991/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/drjseifu1991/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/drjseifu1991/subscriptions',
  organizations_url: 'https://api.github.com/users/drjseifu1991/orgs',
  repos_url: 'https://api.github.com/users/drjseifu1991/repos',
  events_url: 'https://api.github.com/users/drjseifu1991/events{/privacy}',
  received_events_url: 'https://api.github.com/users/drjseifu1991/received_events',
  type: 'User',
  site_admin: false,
  name: 'Dereje Seifu',
  company: '@Merahi Technologies ',
  location: 'Addis Abeba',
  email: null,
  hireable: true,
  bio: null,
  public_repos: 58,
  public_gists: 4,
  followers: 4,
  following: 16,
  created_at: '2019-02-05T23:22:59Z',
  updated_at: '2019-04-17T03:18:31Z',
};
